// Whitelist values from .env file here
module.exports = {
    ENVIRONMENT: process.env.ENVIRONMENT,
    LOG_LEVEL: process.env.LOG_LEVEL,
    BACKEND_URL: process.env.BACKEND_URL,
    FRONTEND_URL: process.env.FRONTEND_URL,
    FRONTEND_HOST: process.env.FRONTEND_HOST,
    API_PREFIX: process.env.API_PREFIX,
    API_PREFIX_CONTENT: process.env.API_PREFIX_CONTENT,
    TOKEN_SALT: process.env.TOKEN_SALT,
    COOKIE_NAME: process.env.COOKIE_NAME,
    COOKIE_PWD: process.env.COOKIE_PWD,
    SESSION_PWD: process.env.SESSION_PWD,
    SESSION_KEY: process.env.SESSION_KEY,
    TOKEN_PUBLIC: process.env.TOKEN_PUBLIC,
    TOKEN_PRIVATE: process.env.TOKEN_PRIVATE,
    CMS_URL: process.env.CMS_URL,
    API_HOST: process.env.API_HOST,
    API_DYNAMIC: process.env.API_DYNAMIC,
    API_LIST_PAGER: process.env.API_LIST_PAGER,
    API_ERROR_PAGE: process.env.API_ERROR_PAGE,
    GA_TRACKING_ID: process.env.GA_TRACKING_ID,
    FB_PIXEL_ID: process.env.FB_PIXEL_ID,
    FB_VERIFICATION_ID: process.env.FB_VERIFICATION_ID,
    FACEBOOK_URL: process.env.FACEBOOK_URL,
    WHATSAPP_URL: process.env.WHATSAPP_URL,
    TWITTER_URL: process.env.TWITTER_URL,
    API_CLIENT_ID: process.env.API_CLIENT_ID,
    API_CLIENT_SECRET: process.env.API_CLIENT_SECRET,
    BACKEND_AJAX_URL: process.env.BACKEND_AJAX_URL,
    NEXT_PUBLIC_RECAPTCHA_SITE_KEY: process.env.NEXT_PUBLIC_RECAPTCHA_SITE_KEY,
    NEXT_PUBLIC_RECAPTCHA_ACTION_NAME:
        process.env.NEXT_PUBLIC_RECAPTCHA_ACTION_NAME,
    JWT_IDENTIFIER: process.env.JWT_IDENTIFIER,
    JWT_CREDENTIAL: process.env.JWT_CREDENTIAL,
    API_TOKEN: process.env.API_TOKEN,
    API_CHAT: process.env.API_CHAT,
    SITE_ID: process.env.SITE_ID,
}
